### PR TITLE
EASYOPAC-1238 - Field on event CT is not places correctly.

### PR DESCRIPTION
**Pull request by bozeak**
https://inlead.atlassian.net/browse/EASYOPAC-1238

### CODE REVIEW

**Comment by guddo** [comment]
Could this not be resolved in ding_event? Where does this field come from?

**Comment by bozeak** [comment]
@guddo This field comes from ding_event module. I can do this in ding_event module, just thought about to not to do changes in core.
Will it be OK to move this into ding_event?

**Comment by guddo** [comment]
This does not happen on a clean ding2 installation, so somehow it must be our diff to ding2 (https://github.com/ding2/ding2/compare/master...easySuite:master) or some modules that does this.

**Comment by bozeak** [comment]
@guddo So, the problem comes from https://github.com/easySuite/ding2/blob/development/themes/ddbasic/templates/node/node--ding-event.tpl.php#L145.

This was added in https://github.com/easySuite/ding2/commit/e217bef86419af256d59c84f6ccbc25c5e4ece9b in order to have possibility to display "Related content", in our case blog posts.

**Pull request closed without merging**
